KBUILD_EXTRA_SYMBOLS=$(src)/../scst/src/Module.symvers

ccflags-y :=	-I$(src)/../scst/include		\
		-Wall					\
		-Wextra					\
		-Wno-type-limits			\
		-Wno-missing-field-initializers		\
		-Wno-unused-parameter			\
		-Wformat				\
		-O2					\
		-Werror=format-security			\
		-Werror=implicit-function-declaration	\
		-pipe					\
		-g					\
		-grecord-gcc-switches			\
		-fstack-clash-protection		\
		-fstack-protector-strong		\
		-Wstrict-prototypes

obj-m := scst_local.o
