KBUILD_EXTRA_SYMBOLS = $(src)/../../scst/src/Module.symvers \
			$(src)/../Module.symvers
ccflags-y += -I$(src)/../../scst/include -I$(src)/.. \
	$(shell [ -n "${REVISION}" ] && echo -DSCST_VERSION_REVISION=${REVISION})
#ccflags-y += -DCONFIG_QLA_TGT_DEBUG_WORK_IN_THREAD
#ccflags-y += -DCONFIG_QLA_TGT_DEBUG_SRR

ifneq ($(BUILD_2X_MODULE),)
ccflags-y += -DCONFIG_SCSI_QLA2XXX_TARGET=y
endif

obj-m := qla2x00tgt.o
qla2x00tgt-objs := qla2x00t.o
