#!/bin/bash

source "$(dirname "$0")/../scripts/kernel-functions" || exit $?

#########################
# Argument verification #
#########################

full_kver="$1"

if [ "${full_kver}" = "" ]; then
  echo "Error: missing kernel version argument."
  exit 1
fi

krel=${full_kver/^*}

mkdir -p qla2xxx-orig
cd qla2xxx-orig || exit $?
download_and_extract_kernel_tree "${full_kver}" || exit $?

touch "linux-${krel}"/drivers/scsi/qla2xxx/*
rm -rf "${krel}"
mkdir -p "${krel}"

mv "linux-${krel}"/drivers/scsi/qla2xxx/* "${krel}"
rm -rf "linux-${krel}"
cd ..
