EXTRA_CFLAGS += -Iinclude/scsi_tgt -Wextra -Wno-unused-parameter

scst-y        += scst_main.o
scst-y        += scst_targ.o
scst-y        += scst_lib.o
scst-y        += scst_proc.o
scst-y        += scst_mem.o
scst-y        += scst_debug.o

obj-$(CONFIG_SCSI_TARGET)   += scst.o dev_handlers/

