#!/bin/bash
#
# A script to prepare a patch for posting on scst-devel@sourceforge.net.
#
# Copyright (C) 2012 Chetan Loke <loke.chetan@gmail.com>
# Copyright (C) 2012 Bart Van Assche <bvanassche@acm.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version 2
# of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

echo "Patch description:"
echo "Your description goes here..."
echo
echo "Signed-off-by: Write your name here <write-your-email-addr@your-host.com>"
echo ---
/usr/bin/svn diff "$@" | /usr/bin/diffstat
echo
/usr/bin/svn diff -x -p "$@"
echo
