#!/bin/bash

usage() {
    echo "Usage: $(basename $0) name version"
}

if [ $# != 2 ]; then
    usage
    exit 1
fi

scriptdir="$(dirname "$0")"
name="$1"
version="$2"

tar --owner=root --group=root --transform="s|^|$name-$version/|" \
  -cjf $name-$version.tar.bz2 $($scriptdir/list-source-files) &&
ls -l $name-$version.tar.bz2
