KBUILD_EXTRA_SYMBOLS=$(src)/../Module.symvers
ccflags-y += -I$(src)/../../include	\
	$(shell [ -n "${REVISION}" ] && echo -DSCST_VERSION_REVISION=${REVISION})
#ccflags-y += -DCONFIG_DEBUG_EXT_COPY_REMAP

obj-m := scst_cdrom.o scst_changer.o scst_disk.o scst_modisk.o scst_tape.o \
	scst_vdisk.o scst_raid.o scst_processor.o scst_user.o
