--- Makefile_orig	2006-03-05 22:07:54.000000000 +0300
+++ Makefile	2006-12-13 14:11:52.000000000 +0300
@@ -8,7 +8,6 @@
 #EXTRA_CFLAGS += -DMPT_DEBUG_EXIT
 #EXTRA_CFLAGS += -DMPT_DEBUG_FAIL
 
-
 #
 # driver/module specifics...
 #
@@ -30,9 +29,19 @@
 #CFLAGS_mptctl.o += -DMPT_DEBUG_IOCTL
 #
 
+SCST_INC_DIR := /usr/local/include/scst
+SCST_DIR := $(SCST_INC_DIR)
+
+CFLAGS_mpt_scst.o += -I$(SCST_INC_DIR) -I$(src)
+CFLAGS_mpt_scst.o += -DEXTRACHECKS
+#CFLAGS_mpt_scst.o += -DTRACING
+#CFLAGS_mpt_scst.o += -DDEBUG
+#CFLAGS_mpt_scst.o += -DDEBUG_WORK_IN_THREAD
+
 #=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-} LSI_LOGIC
 
 obj-$(CONFIG_FUSION_SPI)	+= mptbase.o mptscsih.o mptspi.o
+obj-$(CONFIG_FUSION_SCST)	+= mpt_scst/mpt_scst.o
 obj-$(CONFIG_FUSION_FC)		+= mptbase.o mptscsih.o mptfc.o
 obj-$(CONFIG_FUSION_SAS)	+= mptbase.o mptscsih.o mptsas.o
 obj-$(CONFIG_FUSION_CTL)	+= mptctl.o
