name: Checkpatch upon pull request

on:
  pull_request:
    branches:
      - master

jobs:
  checkpatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Download checkpatch.pl
        run: |
          curl https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl -o checkpatch.pl
          curl https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt -o spelling.txt
          curl https://raw.githubusercontent.com/torvalds/linux/master/scripts/const_structs.checkpatch -o const_structs.checkpatch
          chmod +x checkpatch.pl

      - name: Run checkpatch.pl
        run: |
          CHECKPATCH_PATH=. ./scripts/checkpatch_commits ${{github.event.pull_request.base.sha}}
