name: Run regression tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  regression_tests:
    name: ${{matrix.version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
                  '6.17',
                  '6.16.9',
                  '6.15.11',
                  '6.14.11',
                  '6.13.12',
                  '6.12.49',
                  '6.11.11',
                  '6.10.14',
                  '6.9.12',
                  '6.8.12',
                  '6.7.12',
                  '6.6.108',
                  '6.1.154',
                  '5.15.193',
                  '5.10.244',
                  '5.4.299',
                  '4.19.325',
                  '4.14.336',
                  '4.9.337',
                  '3.18.140',
                  '3.10.108',
                  '6.12.0-55.34.1.el10_0^AlmaLinux^10.0',
                  '5.14.0-570.46.1.el9_6^AlmaLinux^9.6',
                  '5.14.0-503.40.1.el9_5^AlmaLinux^9.5',
                  '5.14.0-427.42.1.el9_4^AlmaLinux^9.4',
                  '5.14.0-362.24.1.el9_3^AlmaLinux^9.3',
                  '5.14.0-284.30.1.el9_2^AlmaLinux^9.2',
                  '5.14.0-162.23.1.el9_1^AlmaLinux^9.1',
                  '5.14.0-70.30.1.el9_0^AlmaLinux^9.0',
                  '4.18.0-553.76.1.el8_10^AlmaLinux^8.10',
                  '4.18.0-513.24.1.el8_9^AlmaLinux^8.9',
                  '4.18.0-477.13.1.el8_8^AlmaLinux^8.8',
                  '4.18.0-425.19.2.el8_7^AlmaLinux^8.7',
                  '4.18.0-372.32.1.el8_6^AlmaLinux^8.6',
                  '4.18.0-348.23.1.el8_5^AlmaLinux^8.5',
                  '4.18.0-305.25.1.el8_4^AlmaLinux^8.4',
                  '4.18.0-240.22.1.el8_3^AlmaLinux^8.3',
                  '3.10.0-1160.118.1.el7^CentOS^7.9.2009',
                  '3.10.0-862.14.4.el7^CentOS^7.5.1804',
                  '6.12.0-103.40.4.3.el10uek^UEK^10',
                  '5.15.0-312.187.5.3.el9uek^UEK^9',
                  '5.4.17-2136.347.6.3.el8uek^UEK^8',
                  '4.14.35-2047.543.3.1.el7uek^UEK^7',
                  '4.1.12-124.93.1.el7uek^UEK^7'
                 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install libelf-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev libsqlite3-dev

      - name: Install sparse
        run: |
          sudo apt-get install sparse

      - name: Install smatch
        run: |
          git clone https://github.com/error27/smatch.git
          cd smatch
          make -j
          sudo BINDIR=/bin SHAREDIR=/home/runner/share make install

      - name: Run regression tests
        run: |
          err=0
          version="${{matrix.version}}"
          workdir="/tmp/scst-${version}"
          out="output.txt"

          ./scripts/run-regression-tests -l -q -d "${workdir}" "${version}-nc-ns-nm" | tee "${out}"

          if ! grep -q "Compiling the patched kernel" "${out}"; then
            echo "::error title=Regression tests::run-regression-tests failed"
            err=1
          else
            if grep -A1 "Compiling the patched kernel" "${out}" | grep -E -q "FAILED|[1-9][0-9]* errors"; then
              echo "::error title=Regression tests::Regression test failed"
              err=1
            else
              echo "::notice title=Regression tests::Succeeded"
            fi

            f=( "${workdir}"/compilation-*-output.txt )
            echo
            echo "===== $(basename "${f[0]}") ====="
            cat "${f[0]}"
          fi

          rm -rf "${workdir}"
          rm -f "${out}"

          exit $err
