name: Run regression tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  regression_tests:
    name: ${{matrix.version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
                  '6.15',
                  '6.14.8',
                  '6.13.12',
                  '6.12.30',
                  '6.11.11',
                  '6.10.14',
                  '6.9.12',
                  '6.8.12',
                  '6.7.12',
                  '6.6.92',
                  '6.1.140',
                  '5.15.184',
                  '5.10.237',
                  '5.4.293',
                  '4.19.325',
                  '4.14.336',
                  '4.9.337',
                  '3.18.140',
                  '3.10.108',
                  '5.14.0-570.12.1.el9_6^AlmaLinux^9.6',
                  '5.14.0-503.40.1.el9_5^AlmaLinux^9.5',
                  '5.14.0-427.42.1.el9_4^AlmaLinux^9.4',
                  '5.14.0-362.24.1.el9_3^AlmaLinux^9.3',
                  '5.14.0-284.30.1.el9_2^AlmaLinux^9.2',
                  '5.14.0-162.23.1.el9_1^AlmaLinux^9.1',
                  '5.14.0-70.30.1.el9_0^AlmaLinux^9.0',
                  '4.18.0-553.53.1.el8_10^AlmaLinux^8.10',
                  '4.18.0-513.24.1.el8_9^AlmaLinux^8.9',
                  '4.18.0-477.13.1.el8_8^AlmaLinux^8.8',
                  '4.18.0-425.19.2.el8_7^AlmaLinux^8.7',
                  '4.18.0-372.32.1.el8_6^AlmaLinux^8.6',
                  '4.18.0-348.23.1.el8_5^AlmaLinux^8.5',
                  '4.18.0-305.25.1.el8_4^AlmaLinux^8.4',
                  '4.18.0-240.22.1.el8_3^AlmaLinux^8.3',
                  '3.10.0-1160.118.1.el7^CentOS^7.9.2009',
                  '3.10.0-862.14.4.el7^CentOS^7.5.1804',
                  '6.12.0-0.20.20.el9uek^UEK^9',
                  '5.15.0-308.179.6.3.el9uek^UEK^9',
                  '5.4.17-2136.343.5.1.el8uek^UEK^8',
                  '4.14.35-2047.543.3.1.el7uek^UEK^7',
                  '4.1.12-124.93.1.el7uek^UEK^7',
                  '4.1.12-124.48.6.el6uek^UEK^6'
                 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install libelf-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev libsqlite3-dev

      - name: Install sparse
        run: |
          sudo apt-get install sparse

      - name: Install smatch
        run: |
          git clone https://github.com/error27/smatch.git
          cd smatch
          make -j
          sudo BINDIR=/bin SHAREDIR=/home/runner/share make install

      - name: Run regression tests
        run: |
          err=0

          ./scripts/run-regression-tests -l -q -k -d /tmp/scst-${{matrix.version}} ${{matrix.version}}-nc-ns-nm | tee output.txt

          if ! grep -q "Compiling the patched kernel" output.txt; then
            echo "::error ::run-regression-tests failed"
            err=1
          else
            if grep -A1 "Compiling the patched kernel" output.txt | grep -E -q "FAILED|[1-9][0-9]* errors"; then
              echo "::error ::Regression test failed"
              err=1
            fi
          fi

          rm -f output.txt

          exit $err
